services:
  - type: web
    name: crm-app
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn salesforce_clone.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: true
      - key: ALLOWED_HOSTS
        value: "crm-test-1-wphx.onrender.com,.onrender.com,localhost,127.0.0.1"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "Admin123!@#"

databases:
  - name: crm-db
    databaseName: crm
    user: crm_user
    plan: free