services:
  - type: web
    name: crm-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn crm.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: .
      - key: DATABASE_URL
        fromDatabase:
          name: crm-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: crm-db
    databaseName: crm
    user: crm_user
    plan: free 