services:
  - type: web
    name: crm-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn salesforce_clone.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: .
      - key: DATABASE_URL
        fromDatabase:
          name: crm-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "crm-test-1-wphx.onrender.com,.onrender.com,localhost,127.0.0.1"

databases:
  - name: crm-db
    databaseName: crm
    user: crm_user
    plan: free 