# Generated by Django 5.1.7 on 2025-03-09 02:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customfield_dashboard_report_dashboardcomponent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model_name', models.CharField(choices=[('Account', 'Account'), ('Contact', 'Contact'), ('Lead', 'Lead'), ('Opportunity', 'Opportunity'), ('Task', 'Task')], max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('entry_criteria', models.TextField(help_text='JSON object of entry criteria')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('step_number', models.IntegerField()),
                ('approval_type', models.CharField(choices=[('unanimous', 'Unanimous'), ('first_response', 'First Response')], max_length=20)),
                ('reject_behavior', models.TextField(help_text='JSON object of rejection behavior')),
                ('approval_actions', models.TextField(help_text='JSON object of approval actions')),
                ('rejection_actions', models.TextField(help_text='JSON object of rejection actions')),
                ('approval_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='crm.approvalprocess')),
                ('approvers', models.ManyToManyField(related_name='approval_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('recalled', 'Recalled')], default='pending', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True)),
                ('approval_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.approvalprocess')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL)),
                ('current_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.approvalstep')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('model_name', models.CharField(choices=[('Account', 'Account'), ('Contact', 'Contact'), ('Lead', 'Lead'), ('Opportunity', 'Opportunity'), ('Task', 'Task')], max_length=20)),
                ('is_html', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('available_merge_fields', models.TextField(help_text='JSON array of available merge fields')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model_name', models.CharField(choices=[('Account', 'Account'), ('Contact', 'Contact'), ('Lead', 'Lead'), ('Opportunity', 'Opportunity'), ('Task', 'Task')], max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('evaluation_criteria', models.CharField(choices=[('created', 'When record is created'), ('created_edited', 'When record is created, and every time it is edited'), ('edited', 'Every time record is edited')], max_length=20)),
                ('conditions', models.TextField(help_text='JSON object of filter conditions')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('action_type', models.CharField(choices=[('field_update', 'Field Update'), ('email_alert', 'Email Alert'), ('task_creation', 'Task Creation'), ('outbound_message', 'Outbound Message')], max_length=20)),
                ('action_config', models.TextField(help_text='JSON object of action configuration')),
                ('order', models.IntegerField(default=0)),
                ('workflow_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='crm.workflowrule')),
            ],
        ),
    ]
